Remove CPS OID and URL from Subscriber Certificate profile
letsencrypt/cp-cps pull request #191
Opened 2023-05-12 21:46 UTC by aarongable

As of BRs version 2.0.0, the inclusion of policy identifiers beyond the BRs DV OID is optional, and the inclusion of CPS URL policy qualifiers for those identifiers is NOT RECOMMENDED. Remove these from our certificate profile, as we intend to remove them from our Subscriber certificates on June 15th.

2023-05-12 23:02 UTC, jsha reviewed
Let's make our CPS OID OPTIONAL so we don't have to time the change.

2023-05-15 21:16 UTC, andygabby requested changes

2023-05-15 21:16 UTC, andygabby commented on CP-CPS.md
> +| Certificate Policies           | CAB Forum Domain Validated (2.23.140.1.2.1) <br>Optionally, ISRG Domain Validated (1.3.6.1.4.1.44947.1.1.1) with qualifier id-qt-cps pointing to this CP/CPS |
Nitpick: Remove trailing space.
```suggestion
| Certificate Policies           | CAB Forum Domain Validated (2.23.140.1.2.1)<br>Optionally, ISRG Domain Validated (1.3.6.1.4.1.44947.1.1.1) with qualifier id-qt-cps pointing to this CP/CPS |
```

2023-05-16 19:41 UTC, bdaehlie approved these changes

2023-05-16 19:41 UTC, andygabby approved these changes

2023-05-16 19:43 UTC, merged